# Generated by Django 4.0.1 on 2022-01-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budenkiln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturecurve',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
